# A Curious Number Machine

This notebook explores the number machines described by Raymond Smullyan in his book "The Lady or the Tiger." 
The characters in the discussion are Inspector Leslie Craig of Scotland Yard and his friend, the inventor Norman McCulloch.
> Now this story takes place in the days before modern computers were invented, but McCulloch had put together a crude mechanical computer of a sort.

McCulloch explains how his mahcine works with numbers:
>(McCulloch) To begin with, by a number I mean a positive whole number... the only numbers my machine handles are those in which 0 does not occur... given two numbers N, M, by NM I don't mean N times M! By NM I mean the number obtained by first writing the digits of N in the order in which they occur, then following it by the digits of M.

In [44]:
#some utilities
def head(x):
    if (x == None):
        return None
    return int(str(x)[0])

def tail(x):
    if (x == None):
        return None
    if (len(str(x))<2):
        return None
    return int(str(x)[1:len(str(x))])

def hasZero(x):
    return str(x).find("0") != -1

def cat(x,y):
    return int(str(x) + str(y))

In [45]:
print(hasZero(301))
print(hasZero(333))
print(head(567))
print(tail(567))
print(cat(123, 456))

True
False
5
67
123456


## Rule 1
> (McCulloch) Let me explain to you the rules of operation. I say X produces a number Y, meaning that X is acceptable and when X is put into the machine, Y is the number that comes out. The first rule is as follows:
>Rule 1: For any number X, 2X is acceptable (2 followed by X, not 2 times X) and 2X produces X.

In [46]:
def rule1(x):
    if (head(x) == 2):
        if (tail(x) != None):
            return int(tail(x))

def rule2(x):
    return None

def machine(x):
    y = rule1(x)
    if (y != None):
        return y
    y = rule2(x)
    if (y != None):
        return y
    return None

In [47]:
print(machine(201))
print(machine(301))
print(machine(229))

1
None
29


## Rule 2
>(McCulloch) For any number X, the number X2X plays a particularly prominent role; I call the number X2X the associate of the number X. 
Rule 2: For any numbers X and Y, if X produces Y, then 3X produces the associate of Y.

In [48]:
def associate(x):
    if (x == None):
        return None
    return int(str(x) + "2" + str(x)) 

def rule2(x):
    if (x == None):
        return None 
    if (head(x) != 3):
        return None
    y = machine(tail(x))
    if (y != None):
        return associate(y)

In [49]:
print(machine(327))
print(machine(32586))
print(machine(3327))
print(machine(3332))


727
5862586
7272727
None


## Some Curious Properties
> (Craig) ... I would like to know just what are the curious features of this machine to which you alluded.

>(McCulloch) To begin with a simple example... there is a number N which produces itself; when you put the number N in, N comes out. Can you find such a number?

In [50]:
x = 323
x1 = machine(x)
print(x)
print(x1)
print(x == x1)

323
323
True


**The number 323 is a fixed point for McCulloch's machine.**

>(McCulloch) There is a number N which produces its own associate, when you put N in N2N comes out.

In [51]:
x = 33233
x1 = machine(x)
x2 = associate(x)
print(x)
print(x1)
print(x2)
print(x1 == x2)

33233
33233233233
33233233233
True


Embedding the fixed point 323 inside of 3x3 gives the number that maps to its own associate.
So, for A = 33233, then machine(A) = associate(A).

> (McCulloch) Next, there is a number N which produces 7N, can you find it?

In [53]:
def map7(x):
    result = str(cat(7,x) == machine(x))
    print (str(x) + "-->" + str(machine(x)) + ", 7N:" + str(cat(7,x)) + " equal: " + result)

# start building off the identity
map7(323)
map7(3273)

323-->323, 7N:7323 equal: False
3273-->73273, 7N:73273 equal: True


Again for this case, building off the fixed point 323, we find that if N = 3273, machine(N) = 7N.

> (McColloch) Is there a number N such that 3N produces the associate of N? i.e. 3N --> N2N

In [75]:
print(machine(323))
print(machine(3323))

323
3232323


Building off the fixed point F = 323. By rule 2, 3F produces the associate of what F produces, but F just produces F, so 3F will produce F2F as required.
So, the N we want here is just the fixed point F = 323.

> (McColloch) And is there an N which produces the associate of 3N.

The associate of 3N would be 3N23N.

In [76]:
def map3N(x):
    r = str(machine(x) == associate(cat(3,x)) )
    print(str(x) + "-->" + str(machine(x)) + " | " + str(associate(cat(3,x))) + ":" + r)

map3N(332333)

332333-->333233323332333 | 333233323332333:True


## McCulloch's Law

Along the way, we noticed that N = 3233 produces 3N, just as N = 3273 produces 7N. Generally N=32X3 produces X32X3. This principle will be called *McCulloch's Law*

In [80]:
print(machine(3253))

53253


>(McColloch) Now, given a number A, is there necessarily some Y such that Y produces the associate of AY? for example, is there a number Y that produces the associate of 56Y, and if so, what number does this?

We saw that N = 332333 produced the associate of 3N... so replacing one of those 3's with A may work...

In [81]:
machine(332533)

533253325332533