# Notebooks for The Mystery of the Monte Carlo Lock 

The first notebook in this set is [here](the_mystery_of_the_monte_carlo_lock.ipynb).

## A Curious Number Machine

The characters in the discussion are Inspector Leslie Craig of Scotland Yard and his friend, the inventor Norman McCulloch.
> Now this story takes place in the days before modern computers were invented, but McCulloch had put together a crude mechanical computer of a sort.

McCulloch explains how his mahcine works with numbers:
>(McCulloch) To begin with, by a number I mean a positive whole number... the only numbers my machine handles are those in which 0 does not occur... given two numbers N, M, by NM I don't mean N times M! By NM I mean the number obtained by first writing the digits of N in the order in which they occur, then following it by the digits of M.

In [1]:
#some utilities
def head(x):
    if (x == None):
        return None
    return int(str(x)[0])

def tail(x):
    if (x == None):
        return None
    if (len(str(x))<2):
        return None
    return int(str(x)[1:len(str(x))])

def hasZero(x):
    return str(x).find("0") != -1

def cat(x,y):
    return int(str(x) + str(y))

In [2]:
print(hasZero(301))
print(hasZero(333))
print(head(567))
print(tail(567))
print(cat(123, 456))

True
False
5
67
123456


## Rule 1
> (McCulloch) Let me explain to you the rules of operation. I say X produces a number Y, meaning that X is acceptable and when X is put into the machine, Y is the number that comes out. The first rule is as follows:
>Rule 1: For any number X, 2X is acceptable (2 followed by X, not 2 times X) and 2X produces X.

In [3]:
def rule1(x):
    if (head(x) == 2):
        if (tail(x) != None):
            return int(tail(x))

def rule2(x):
    return None

def machine(x):
    if (hasZero(x)):
        return None
    y = rule1(x)
    if (y != None):
        return y
    y = rule2(x)
    if (y != None):
        return y
    return None

In [4]:
print(machine(201))
print(machine(301))
print(machine(229))

None
None
29


## Rule 2
>(McCulloch) For any number X, the number X2X plays a particularly prominent role; I call the number X2X the associate of the number X. 
Rule 2: For any numbers X and Y, if X produces Y, then 3X produces the associate of Y.

In [5]:
def associate(x):
    if (x == None):
        return None
    return int(str(x) + "2" + str(x)) 

def rule2(x):
    if (x == None):
        return None 
    if (head(x) != 3):
        return None
    y = machine(tail(x))
    if (y != None):
        return associate(y)

In [6]:
print(machine(327))
print(machine(32586))
print(machine(3327))
print(machine(3332))


727
5862586
7272727
None


> (McCulloch) No number consisting entirely of 3's is acceptable. Also 32 is not acceptable, nor is 332, nore any string of 3's followed by 2. But for any nmber X, 2X is acceptable; 32X is acceptable; 332X and 3332X is acceptable; and so forth. In short, the only acceptable numbers are 2X, 32X, 332X, 3332X, and any string of 3's followed by 2X. And, 2X produces X, 32X produces the associate of X, 332X produces the associate of the associate of X, which it is convenient to call the double associate of X.

In [7]:
print(machine(2))
print(machine(3))
print(machine(32))
print(machine(332))
print(machine(21))
print(machine(321))
print(machine(3321))

None
None
None
None
1
121
1212121


## Some Curious Properties
> (Craig) ... I would like to know just what are the curious features of this machine to which you alluded.

### section 1, page 113
>(McCulloch) To begin with a simple example... there is a number N which produces itself; when you put the number N in, N comes out. Can you find such a number?

In [8]:
x = 323
x1 = machine(x)
print(x)
print(x1)
print(x == x1)

323
323
True


**The number 323 is a fixed point for McCulloch's machine.**

### section 2, page 113
>(McCulloch) There is a number N which produces its own associate, when you put N in N2N comes out.

In [9]:
x = 33233
x1 = machine(x)
x2 = associate(x)
print(x)
print(x1)
print(x2)
print(x1 == x2)

33233
33233233233
33233233233
True


Embedding the fixed point 323 inside of 3x3 gives the number that maps to its own associate.
So, for A = 33233, then machine(A) = associate(A).

### section 5, page 114
> (McCulloch) Next, there is a number N which produces 7N, can you find it?

In [10]:
def map7(x):
    result = str(cat(7,x) == machine(x))
    print (str(x) + "-->" + str(machine(x)) + ", 7N:" + str(cat(7,x)) + " equal: " + result)

# start building off the identity
map7(323)
map7(3273)

323-->323, 7N:7323 equal: False
3273-->73273, 7N:73273 equal: True


Again for this case, building off the fixed point 323, we find that if N = 3273, machine(N) = 7N.

### section 6, page 114
> (McColloch) Is there a number N such that 3N produces the associate of N? i.e. 3N --> N2N

In [11]:
print(machine(323))
print(machine(3323))

323
3232323


Building off the fixed point F = 323. By rule 2, 3F produces the associate of what F produces, but F just produces F, so 3F will produce F2F as required.
So, the N we want here is just the fixed point F = 323.

### section 7, page 114
> (McColloch) And is there an N which produces the associate of 3N.

The associate of 3N would be 3N23N.

In [12]:
def map3N(x):
    r = str(machine(x) == associate(cat(3,x)) )
    print(str(x) + "-->" + str(machine(x)) + " | " + str(associate(cat(3,x))) + ":" + r)

map3N(332333)

332333-->333233323332333 | 333233323332333:True


### section 8, page 114
Along the way, we noticed that N = 3233 produces 3N, just as N = 3273 produces 7N. Generally N=32X3 produces X32X3. This principle will be called *McCulloch's Law*

In [13]:
def mapMcL(a):
    y = int("32" + str(a) + "3")
    ay = cat(a,y)
    print(str(a) + "-->" + str(y) + ", " + str(y) +"-->" + str(machine(y)) + " | " + str((ay)))

mapMcL(3)
mapMcL(54)
mapMcL(1234)

3-->3233, 3233-->33233 | 33233
54-->32543, 32543-->5432543 | 5432543
1234-->3212343, 3212343-->12343212343 | 12343212343


### section 9, page 115
>(McColloch) Now, given a number A, is there necessarily some Y such that Y produces the associate of AY? for example, is there a number Y that produces the associate of 56Y, and if so, what number does this?

We saw that N = 332333 produced the associate of 3N... so replacing one of those 3's with A may work...

In [14]:
def mapAY(a):
    y = int("332" + str(a) + "33")
    ay = cat(a,y)
    print(str(a) + "-->" + str(y) + ", " + str(y) +"-->" + str(machine(y)) + " | " + str(associate(ay)))

mapAY(5)
mapAY(44)

5-->332533, 332533-->533253325332533 | 533253325332533
44-->3324433, 3324433-->4433244332443324433 | 4433244332443324433


### section 10, page 115
> (McCulloch) Another interesting thing, is that there is a number N that produces its own double associate. Can you find it?

In [15]:
x = 3332333
print(machine(x))
print(associate(associate(x)))
print(machine(x) == associate(associate(x)))


3332333233323332333233323332333
3332333233323332333233323332333
True


### section 11, page 115
>(McCulloch) Also, given any number A there is a number X that produces the double associate of AX. Can you see how to find such an X, given the number A?

In [18]:
def mapDAY(a):
    y = int("3332" + str(a) + "333")
    ay = cat(a,y)
    print(str(a) + "-->" + str(y) + ", " + str(y) +"-->" + str(machine(y)))
    print("double associate of " + str(ay) + ": " + str(associate(associate(ay))))
    r = (machine(y) == associate(associate(ay)))
    print(str(r))

mapDAY(5)
mapDAY(44)

5-->33325333, 33325333-->533325333253332533325333253332533325333
double associate of 533325333: 533325333253332533325333253332533325333
True
44-->333244333, 333244333-->44333244333244333244333244333244333244333244333
double associate of 44333244333: 44333244333244333244333244333244333244333244333
True


### section 19, page 117
>Find a number N such that N produces N23

In [19]:
x = 32323
print(machine(x))
print(cat(x, 23))
# 32323 produces the associate of what 2323 produces. 2323 produces 323 associate of 323 is 3232323, 
# which is 32323 23 as required.

3232323
3232323
